version: "3.9"

services: 
  db:
    image: postgres:13.3
    container_name: rentx_db
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_DB=rentx
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: always

volumes:
  pgdata:
   driver: local
    